### ISSUE TITLE
Ubanut connection error

### ISSUE THREAD

**Issue by ForgetV** [thomashuang/Fukei#5]
ss-server
Traceback (most recent call last):
  File "/usr/local/bin/ss-server", line 4, in <module>
    __import__('pkg_resources').run_script('fukei==0.1', 'ss-server')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/fukei-0.1-py2.7.egg/EGG-INFO/scripts/ss-server", line 9, in <module>
    
  File "build/bdist.linux-x86_64/egg/fukei/server.py", line 3, in <module>
ImportError: No module named tornado.ioloop

**Comment by whiteclover** [comment]
did you install tornado module?
